# Что такое Pandas

Pandas — это библиотека Python для работы с таблицами (как Excel, но в коде).

Основные структуры:

Series — один столбец

DataFrame — таблица (строки + столбцы)

pip install pandas

In [35]:
import pandas as pd

# Создание DataFrame
# 1. Из словаря

In [36]:
data = {
    "name": ["Anna", "Ivan", "Ali"],
    "age": [20, 22, 19],
    "grade": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

   name  age  grade
0  Anna   20     85
1  Ivan   22     90
2   Ali   19     78

# Загрузка данных
# CSV

In [37]:
df = pd.read_csv("music_catalog.xlsx.csv")

# Excel

df = pd.read_excel("students.xlsx")

# Просмотр данных

In [38]:
df.head()     # первые 5 строк
df.tail()     # последние 5
df.info()     # информация о данных
df.describe() # статистика

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track_ID          10000 non-null  object
 1   Title             10000 non-null  object
 2   Artist            10000 non-null  object
 3   Album             10000 non-null  object
 4   Year              10000 non-null  int64
 5   Genre             10000 non-null  object
 6   Duration_sec      10000 non-null  int64
 7   BPM               10000 non-null  int64
 8   Key               10000 non-null  object
 9   Energy            10000 non-null  object
 10  Danceability      10000 non-null  object
 11  Acousticness      10000 non-null  object
 12  Instrumentalness  10000 non-null  object
 13  Liveness          10000 non-null  object
 14  Valence           10000 non-null  object
 15  Popularity        10000 non-null  int64
 16  Streams_million   10000 non-null  object
 17  Explicit          10000 non-null  int64
 18  Country           10000 non-null  object
 19  Language          10000 non-null  object
 20  Record_Label      10000 non-null  object
 21  Awards_won        10000 non-null  int64
 22  Awards_nominated  10000 non-null  int64
 23  Is_Favorite       10000 non-null  int64
 24  User_Rating       10000 non-null  object
dtypes: int64(8), object(17)
memory usage: 1.9+ MB

,Year,Duration_sec,BPM,Popularity,Explicit,Awards_won,Awards_nominated,Is_Favorite
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,1996.535700,328.943900,129.396800,49.784900,0.507700,24.611900,49.57540,0.498500
std,15.586007,156.492199,40.351374,29.011325,0.499966,14.362726,29.09283,0.500023
min,1970.000000,60.000000,60.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,1983.000000,193.000000,95.000000,25.000000,0.000000,12.000000,24.00000,0.000000
50%,1996.000000,328.000000,129.000000,50.000000,1.000000,25.000000,50.00000,0.000000
75%,2010.000000,467.000000,165.000000,75.000000,1.000000,37.000000,75.00000,1.000000
max,2023.000000,599.000000,199.000000,100.000000,1.000000,49.000000,99.00000,1.000000

# Выбор данных
Столбец

df["name"]

Несколько столбцов

df[["name", "age"]]

Строка по индексу

df.iloc[0]

In [39]:
print(df["Language"] )

0       Japanese
1         Korean
2        Spanish
3         German
4         French
          ...
9995      French
9996    Japanese
9997    Japanese
9998    Japanese
9999     English
Name: Language, Length: 10000, dtype: object

In [40]:
print(df[["Genre", "Duration_sec"]])

           Genre  Duration_sec
0           Rock           139
1           Jazz           101
2        Hip-Hop           443
3           Rock           531
4           Jazz           518
...          ...           ...
9995     Hip-Hop           390
9996   Classical           296
9997  Electronic           356
9998  Electronic           223
9999   Classical            79

[10000 rows x 2 columns]

In [41]:
df.iloc[0]

Track_ID               Track_0
Title                   Song_0
Artist              Artist_511
Album                 Album_83
Year                      1972
Genre                     Rock
Duration_sec               139
BPM                         72
Key                         G#
Energy                    0,51
Danceability              0,85
Acousticness               0,3
Instrumentalness          0,19
Liveness                  0,34
Valence                   0,87
Popularity                  22
Streams_million         290,82
Explicit                     1
Country                     UK
Language              Japanese
Record_Label         Label_119
Awards_won                  32
Awards_nominated            77
Is_Favorite                  1
User_Rating                9,1
Name: 0, dtype: object

# Фильтрация

In [42]:
print(df[df["Popularity"] > 99])

        Track_ID      Title      Artist      Album  Year       Genre  \
151    Track_151   Song_151   Artist_87  Album_472  1987        Jazz
276    Track_276   Song_276  Artist_613  Album_196  1982        Jazz
434    Track_434   Song_434  Artist_468   Album_86  1983     Hip-Hop
480    Track_480   Song_480  Artist_626  Album_353  1993         Pop
728    Track_728   Song_728  Artist_758  Album_277  2020        Jazz
...          ...        ...         ...        ...   ...         ...
9469  Track_9469  Song_9469  Artist_891  Album_332  1994         Pop
9500  Track_9500  Song_9500  Artist_220  Album_409  1972   Classical
9832  Track_9832  Song_9832   Artist_22  Album_389  2012   Classical
9915  Track_9915  Song_9915  Artist_229   Album_99  1972         Pop
9953  Track_9953  Song_9953  Artist_341  Album_158  1985  Electronic

      Duration_sec  BPM Key Energy  ... Popularity Streams_million Explicit  \
151            555  132   E   0,83  ...        100          336,58        0
276            571   87   D   0,09  ...        100           52,93        1
434             86  180  A#   0,31  ...        100           54,53        0
480            127   62  C#   0,98  ...        100           56,51        1
728            234  185   B   0,57  ...        100          136,52        1
...            ...  ...  ..    ...  ...        ...             ...      ...
9469           140  116   C   0,98  ...        100          213,46        1
9500           101  147  A#   0,21  ...        100          202,68        1
9832            90  134   E   0,49  ...        100           85,77        1
9915           109  193   C   0,55  ...        100           114,6        0
9953           197  193   A   0,06  ...        100          247,88        1

          Country  Language  Record_Label Awards_won  Awards_nominated  \
151           USA   Spanish     Label_134          7                48
276         Japan    Korean     Label_155         39                67
434   South Korea    French       Label_8         44                64
480         Japan    Korean      Label_88         37                19
728            UK   Spanish      Label_35         29                43
...           ...       ...           ...        ...               ...
9469       France    Korean      Label_84         46                 3
9500       France    Korean      Label_42         10                 9
9832       Canada    French     Label_164         38                68
9915       France  Japanese      Label_67         34                95
9953       France   Spanish      Label_33         22                51

     Is_Favorite User_Rating
151            1           2
276            0         8,8
434            0         9,4
480            0         5,7
728            1         6,1
...          ...         ...
9469           0         8,1
9500           1         5,8
9832           0         5,1
9915           1         6,9
9953           0         2,8

[88 rows x 25 columns]

In [43]:
print(df[(df["Genre"] == "Hip-Hop") & (df["Popularity"] > 99)])

        Track_ID      Title      Artist      Album  Year    Genre  \
434    Track_434   Song_434  Artist_468   Album_86  1983  Hip-Hop
1523  Track_1523  Song_1523  Artist_506  Album_109  2018  Hip-Hop
2250  Track_2250  Song_2250  Artist_155  Album_109  1995  Hip-Hop
2657  Track_2657  Song_2657  Artist_742  Album_474  2010  Hip-Hop
2842  Track_2842  Song_2842  Artist_679  Album_151  1991  Hip-Hop
4301  Track_4301  Song_4301  Artist_951  Album_422  1979  Hip-Hop
4604  Track_4604  Song_4604  Artist_981  Album_177  2009  Hip-Hop
5286  Track_5286  Song_5286  Artist_297   Album_58  1987  Hip-Hop
5531  Track_5531  Song_5531  Artist_939  Album_252  1984  Hip-Hop
6395  Track_6395  Song_6395  Artist_108  Album_265  1983  Hip-Hop
7100  Track_7100  Song_7100  Artist_487  Album_483  2003  Hip-Hop
7546  Track_7546  Song_7546   Artist_58  Album_112  1975  Hip-Hop
7728  Track_7728  Song_7728  Artist_810  Album_293  2019  Hip-Hop
8210  Track_8210  Song_8210  Artist_157  Album_476  2022  Hip-Hop
8668  Track_8668  Song_8668  Artist_790  Album_215  2020  Hip-Hop
9062  Track_9062  Song_9062  Artist_340   Album_19  2010  Hip-Hop

      Duration_sec  BPM Key Energy  ... Popularity Streams_million Explicit  \
434             86  180  A#   0,31  ...        100           54,53        0
1523           272  185   B   0,42  ...        100           77,94        0
2250           409  196  A#   0,51  ...        100           21,47        0
2657            98   78   F   0,54  ...        100           77,84        1
2842           161  187   F   0,12  ...        100          478,06        0
4301           186   70  G#   0,02  ...        100          191,98        1
4604           294   98  G#   0,41  ...        100           55,36        1
5286           284   88   C   0,19  ...        100          120,91        0
5531           127  127   G   0,28  ...        100          340,65        0
6395           210   64   F   0,85  ...        100          176,01        1
7100           410  126  D#    0,4  ...        100          353,87        1
7546           203  151   B   0,68  ...        100          377,79        0
7728           577  180  F#   0,03  ...        100          401,63        1
8210           439  102   G   0,75  ...        100          154,51        0
8668           351   82  G#   0,42  ...        100          269,14        1
9062           432   85   A   0,41  ...        100          204,68        1

          Country  Language  Record_Label Awards_won  Awards_nominated  \
434   South Korea    French       Label_8         44                64
1523           UK  Japanese      Label_61         34                11
2250          USA    Korean      Label_83         10                95
2657          USA    German      Label_29         17                18
2842          USA   English      Label_90         36                70
4301          USA    Korean      Label_63         29                74
4604      Germany    French     Label_127         14                92
5286  South Korea    French     Label_190         17                12
5531       France   English       Label_7         22                43
6395       France  Japanese     Label_107         39                80
7100        Japan  Japanese      Label_46         39                65
7546        Japan   Spanish      Label_53         11                15
7728      Germany   Spanish     Label_165         31                30
8210        Japan    Korean      Label_68         28                86
8668       France    French     Label_175         39                73
9062  South Korea   Spanish     Label_154         22                57

     Is_Favorite User_Rating
434            0         9,4
1523           1         8,5
2250           1         1,3
2657           1         7,8
2842           0           9
4301           0         6,9
4604           1         5,8
5286           1         7,5
5531           0         1,5
6395           1         5,3
7100           1         8,3
7546           0         4,5
7728           1         6,2
8210           0         2,4
8668           0         5,6
9062           1         8,5

[16 rows x 25 columns]

# Добавление столбца

In [44]:
df["passed"] = df["Popularity"] > 80
df.head()

,Track_ID,Title,Artist,Album,Year,Genre,Duration_sec,BPM,Key,Energy,...,Streams_million,Explicit,Country,Language,Record_Label,Awards_won,Awards_nominated,Is_Favorite,User_Rating,passed
0,Track_0,Song_0,Artist_511,Album_83,1972,Rock,139,72,G#,"0,51",...,"290,82",1,UK,Japanese,Label_119,32,77,1,"9,1",False
1,Track_1,Song_1,Artist_366,Album_91,1977,Jazz,101,93,F,"0,8",...,"365,97",0,Germany,Korean,Label_19,43,30,0,"8,1",False
2,Track_2,Song_2,Artist_383,Album_467,2003,Hip-Hop,443,107,F,"0,05",...,"301,37",1,USA,Spanish,Label_83,0,32,0,"8,7",True
3,Track_3,Song_3,Artist_323,Album_451,2014,Rock,531,146,B,"0,08",...,"310,72",0,Canada,German,Label_80,19,38,0,"8,3",False
4,Track_4,Song_4,Artist_989,Album_154,2009,Jazz,518,99,F,"0,72",...,"443,28",1,UK,French,Label_192,7,13,1,"2,1",False

In [45]:
print(df["Popularity"])

0       22
1       15
2       90
3       39
4       72
        ..
9995    65
9996    67
9997    43
9998    52
9999     5
Name: Popularity, Length: 10000, dtype: int64

# Изменение данных

In [46]:
df["Popularity"] = df["Popularity"] + 1
print(df["Popularity"])

0       23
1       16
2       91
3       40
4       73
        ..
9995    66
9996    68
9997    44
9998    53
9999     6
Name: Popularity, Length: 10000, dtype: int64

# Удаление

In [47]:
df.drop("Energy", axis=1, inplace=True)  # столбец
df.head()

,Track_ID,Title,Artist,Album,Year,Genre,Duration_sec,BPM,Key,Danceability,...,Streams_million,Explicit,Country,Language,Record_Label,Awards_won,Awards_nominated,Is_Favorite,User_Rating,passed
0,Track_0,Song_0,Artist_511,Album_83,1972,Rock,139,72,G#,"0,85",...,"290,82",1,UK,Japanese,Label_119,32,77,1,"9,1",False
1,Track_1,Song_1,Artist_366,Album_91,1977,Jazz,101,93,F,"0,1",...,"365,97",0,Germany,Korean,Label_19,43,30,0,"8,1",False
2,Track_2,Song_2,Artist_383,Album_467,2003,Hip-Hop,443,107,F,"0,36",...,"301,37",1,USA,Spanish,Label_83,0,32,0,"8,7",True
3,Track_3,Song_3,Artist_323,Album_451,2014,Rock,531,146,B,"0,63",...,"310,72",0,Canada,German,Label_80,19,38,0,"8,3",False
4,Track_4,Song_4,Artist_989,Album_154,2009,Jazz,518,99,F,"0,73",...,"443,28",1,UK,French,Label_192,7,13,1,"2,1",False

# Группировка (очень важно!)

Например:

средний балл у сдавших

средний возраст по группам

In [48]:
print(df.groupby("passed")["Popularity"].mean())

passed
False    41.064468
True     91.325233
Name: Popularity, dtype: float64

In [49]:
print(df.sort_values(by="Popularity", ascending=False))

        Track_ID      Title      Artist      Album  Year       Genre  \
9441  Track_9441  Song_9441  Artist_436  Album_391  1978         Pop
4457  Track_4457  Song_4457  Artist_748  Album_379  1975        Rock
5079  Track_5079  Song_5079  Artist_533  Album_471  2006  Electronic
8210  Track_8210  Song_8210  Artist_157  Album_476  2022     Hip-Hop
5513  Track_5513  Song_5513  Artist_187  Album_496  1997   Classical
...          ...        ...         ...        ...   ...         ...
5168  Track_5168  Song_5168  Artist_886  Album_344  1981     Hip-Hop
4986  Track_4986  Song_4986   Artist_47  Album_182  1981     Hip-Hop
4888  Track_4888  Song_4888   Artist_63  Album_187  1988  Electronic
4870  Track_4870  Song_4870  Artist_564   Album_48  2009     Hip-Hop
9422  Track_9422  Song_9422  Artist_197  Album_309  1982  Electronic

      Duration_sec  BPM Key Danceability  ... Streams_million Explicit  \
9441            90  139   D         0,22  ...          178,42        0
4457           498  148  D#         0,81  ...          417,89        1
5079           227  138  C#         0,53  ...          179,09        0
8210           439  102   G         0,72  ...          154,51        0
5513           365  198   B         0,56  ...          169,82        0
...            ...  ...  ..          ...  ...             ...      ...
5168           527  119   A         0,76  ...           87,55        0
4986           436  140  F#         0,32  ...           466,6        1
4888           146  190   D         0,64  ...          428,14        0
4870           476   76  F#         0,58  ...          409,01        1
9422           390  155   D         0,91  ...           466,9        1

          Country Language  Record_Label Awards_won  Awards_nominated  \
9441       Canada  Spanish     Label_174         10                48
4457          USA  English       Label_6         22                28
5079      Germany   German      Label_86         34                59
8210        Japan   Korean      Label_68         28                86
5513           UK  Spanish     Label_193          2                54
...           ...      ...           ...        ...               ...
5168          USA  English      Label_24         38                 1
4986  South Korea  English     Label_174         20                27
4888        Japan   German     Label_158         27                25
4870       France  Spanish     Label_145          1                 9
9422          USA   German     Label_145          9                16

     Is_Favorite User_Rating passed
9441           1           3   True
4457           1         3,2   True
5079           0         3,3   True
8210           0         2,4   True
5513           0         2,8   True
...          ...         ...    ...
5168           1         6,1  False
4986           1         7,5  False
4888           1         1,3  False
4870           0         8,1  False
9422           0           3  False

[10000 rows x 25 columns]

# Работа с пропусками

df.isnull()       # где пусто
df.dropna()       # удалить пустые
df.fillna(0)      # заменить

# Сохранение

df.to_csv("output.csv", index=False)

df.to_excel("output.xlsx", index=False)

# 1. Работа с .loc и .iloc (очень важно!)
iloc → как координаты (0,1)

loc → как Excel (по имени столбца)



#### .iloc — по индексам

In [50]:
df.iloc[0]        # первая строка
df.iloc[0:3]      # строки 0-2
df.iloc[0, 1]     # строка 0, столбец 1

'Song_0'

#### .loc — по названиям

In [51]:
print(df.loc[0, "Country"])
print(df.loc[df["Popularity"] > 80, ["Country", "Popularity"]])

UK
      Country  Popularity
2         USA          91
9     Germany          88
27         UK          82
31    Germany          82
36      Japan          96
...       ...         ...
9970   France          86
9979  Germany          88
9982   Canada          89
9983      USA          92
9989   France          94

[2036 rows x 2 columns]

# Применение функций (apply)

In [52]:
def grade_category(x):
    if x >= 90:
        return "A"
    elif x >= 75:
        return "B"
    else:
        return "C"

df["category"] = df["Popularity"].apply(grade_category)
print(df.head())

  Track_ID   Title      Artist      Album  Year    Genre  Duration_sec  BPM  \
0  Track_0  Song_0  Artist_511   Album_83  1972     Rock           139   72
1  Track_1  Song_1  Artist_366   Album_91  1977     Jazz           101   93
2  Track_2  Song_2  Artist_383  Album_467  2003  Hip-Hop           443  107
3  Track_3  Song_3  Artist_323  Album_451  2014     Rock           531  146
4  Track_4  Song_4  Artist_989  Album_154  2009     Jazz           518   99

  Key Danceability  ... Explicit  Country  Language Record_Label  Awards_won  \
0  G#         0,85  ...        1       UK  Japanese    Label_119          32
1   F          0,1  ...        0  Germany    Korean     Label_19          43
2   F         0,36  ...        1      USA   Spanish     Label_83           0
3   B         0,63  ...        0   Canada    German     Label_80          19
4   F         0,73  ...        1       UK    French    Label_192           7

  Awards_nominated  Is_Favorite User_Rating passed category
0               77            1         9,1  False        C
1               30            0         8,1  False        C
2               32            0         8,7   True        A
3               38            0         8,3  False        C
4               13            1         2,1  False        C

[5 rows x 26 columns]

# Быстрые операции (без apply — лучше!)

In [53]:
df["category"] = "C"
df.loc[df["Popularity"] >= 75, "category"] = "B"
df.loc[df["Popularity"] >= 90, "category"] = "A"

# GroupBy — самое важное
Идея:

“Разделили на группы → посчитали”

In [54]:
df.groupby("Genre")["Popularity"].mean()

Genre
Classical     51.323988
Electronic    51.140466
Hip-Hop       49.817921
Jazz          50.309392
Pop           51.663063
Rock          50.509781
Name: Popularity, dtype: float64

# или

In [56]:
df.groupby("Artist").agg({
    "Popularity": "mean",
    "Awards_won": "sum"
})

# Перевод:

# для каждого артиста:

# средняя популярность
# сколько наград всего

            Popularity  Awards_won
Artist
Artist_1     44.250000         229
Artist_10    54.800000          97
Artist_100   35.500000         248
Artist_101   60.818182         311
Artist_102   61.666667         212
...                ...         ...
Artist_995   39.142857         138
Artist_996   49.000000         229
Artist_997   54.000000         183
Artist_998   55.000000         392
Artist_999   52.500000         207

[999 rows x 2 columns]

# Pivot table (сводная)
Это просто “красивый groupby”

In [57]:
df.pivot_table(
    values="Popularity",
    index="Genre",
    aggfunc="mean"
)

            Popularity
Genre
Classical    51.323988
Electronic   51.140466
Hip-Hop      49.817921
Jazz         50.309392
Pop          51.663063
Rock         50.509781

# Создание новых признаков (Feature Engineering)

In [58]:
df["is_long"] = df["Duration_sec"] > 300 
print(df.head())

  Track_ID   Title      Artist      Album  Year    Genre  Duration_sec  BPM  \
0  Track_0  Song_0  Artist_511   Album_83  1972     Rock           139   72
1  Track_1  Song_1  Artist_366   Album_91  1977     Jazz           101   93
2  Track_2  Song_2  Artist_383  Album_467  2003  Hip-Hop           443  107
3  Track_3  Song_3  Artist_323  Album_451  2014     Rock           531  146
4  Track_4  Song_4  Artist_989  Album_154  2009     Jazz           518   99

  Key Danceability  ...  Country  Language Record_Label Awards_won  \
0  G#         0,85  ...       UK  Japanese    Label_119         32
1   F          0,1  ...  Germany    Korean     Label_19         43
2   F         0,36  ...      USA   Spanish     Label_83          0
3   B         0,63  ...   Canada    German     Label_80         19
4   F         0,73  ...       UK    French    Label_192          7

   Awards_nominated Is_Favorite  User_Rating passed category is_long
0                77           1          9,1  False        C   False
1                30           0          8,1  False        C   False
2                32           0          8,7   True        A    True
3                38           0          8,3  False        C    True
4                13           1          2,1  False        C    True

[5 rows x 27 columns]

In [59]:
###  Пример: популярность категориями

In [60]:
df["pop_level"] = "low"
df.loc[df["Popularity"] > 50, "pop_level"] = "medium"
df.loc[df["Popularity"] > 80, "pop_level"] = "high" 
print(df.head())

  Track_ID   Title      Artist      Album  Year    Genre  Duration_sec  BPM  \
0  Track_0  Song_0  Artist_511   Album_83  1972     Rock           139   72
1  Track_1  Song_1  Artist_366   Album_91  1977     Jazz           101   93
2  Track_2  Song_2  Artist_383  Album_467  2003  Hip-Hop           443  107
3  Track_3  Song_3  Artist_323  Album_451  2014     Rock           531  146
4  Track_4  Song_4  Artist_989  Album_154  2009     Jazz           518   99

  Key Danceability  ...  Language Record_Label Awards_won Awards_nominated  \
0  G#         0,85  ...  Japanese    Label_119         32               77
1   F          0,1  ...    Korean     Label_19         43               30
2   F         0,36  ...   Spanish     Label_83          0               32
3   B         0,63  ...    German     Label_80         19               38
4   F         0,73  ...    French    Label_192          7               13

   Is_Favorite User_Rating  passed category is_long pop_level
0            1         9,1   False        C   False       low
1            0         8,1   False        C   False       low
2            0         8,7    True        A    True      high
3            0         8,3   False        C    True       low
4            1         2,1   False        C    True    medium

[5 rows x 28 columns]

# Бинирование (разбиение на группы)
Делим числа на категории

In [62]:
df["pop_group"] = pd.cut(
    df["Popularity"],
    bins=[0, 30, 70, 100],
    labels=["low", "medium", "high"]
)
print(df.head())
#разбили популярность на интервалы как оценки (2,3,4,5)

  Track_ID   Title      Artist      Album  Year    Genre  Duration_sec  BPM  \
0  Track_0  Song_0  Artist_511   Album_83  1972     Rock           139   72
1  Track_1  Song_1  Artist_366   Album_91  1977     Jazz           101   93
2  Track_2  Song_2  Artist_383  Album_467  2003  Hip-Hop           443  107
3  Track_3  Song_3  Artist_323  Album_451  2014     Rock           531  146
4  Track_4  Song_4  Artist_989  Album_154  2009     Jazz           518   99

  Key Danceability  ... Record_Label Awards_won Awards_nominated Is_Favorite  \
0  G#         0,85  ...    Label_119         32               77           1
1   F          0,1  ...     Label_19         43               30           0
2   F         0,36  ...     Label_83          0               32           0
3   B         0,63  ...     Label_80         19               38           0
4   F         0,73  ...    Label_192          7               13           1

   User_Rating passed  category is_long pop_level pop_group
0          9,1  False         C   False       low       low
1          8,1  False         C   False       low       low
2          8,7   True         A    True      high      high
3          8,3  False         C    True       low    medium
4          2,1  False         C    True    medium      high

[5 rows x 29 columns]

# Работа с несколькими условиями (np.where)

In [63]:
import numpy as np

df["hit"] = np.where(
    (df["Popularity"] > 80) & (df["Streams_million"] > 500),
    "yes",
    "no"
)

TypeError: '>' not supported between instances of 'str' and 'int'

# Сортировка + топы (очень полезно)
Топ треков

In [64]:
print(df.nlargest(10, "Popularity"))

        Track_ID      Title      Artist      Album  Year       Genre  \
151    Track_151   Song_151   Artist_87  Album_472  1987        Jazz
276    Track_276   Song_276  Artist_613  Album_196  1982        Jazz
434    Track_434   Song_434  Artist_468   Album_86  1983     Hip-Hop
480    Track_480   Song_480  Artist_626  Album_353  1993         Pop
728    Track_728   Song_728  Artist_758  Album_277  2020        Jazz
866    Track_866   Song_866  Artist_116  Album_465  1973         Pop
1094  Track_1094  Song_1094  Artist_169  Album_240  2018        Rock
1342  Track_1342  Song_1342  Artist_495   Album_56  2015         Pop
1523  Track_1523  Song_1523  Artist_506  Album_109  2018     Hip-Hop
1664  Track_1664  Song_1664  Artist_353  Album_239  1986  Electronic

      Duration_sec  BPM Key Danceability  ... Record_Label Awards_won  \
151            555  132   E         0,14  ...    Label_134          7
276            571   87   D         0,85  ...    Label_155         39
434             86  180  A#         0,85  ...      Label_8         44
480            127   62  C#         0,39  ...     Label_88         37
728            234  185   B         0,75  ...     Label_35         29
866            287  137  C#         0,75  ...    Label_151         17
1094           368  113  D#         0,56  ...     Label_84         31
1342           123   95   E         0,65  ...    Label_145         38
1523           272  185   B         0,22  ...     Label_61         34
1664           333  106   B          0,2  ...     Label_79         12

     Awards_nominated Is_Favorite  User_Rating passed  category is_long  \
151                48           1            2   True         A    True
276                67           0          8,8   True         A    True
434                64           0          9,4   True         A   False
480                19           0          5,7   True         A   False
728                43           1          6,1   True         A   False
866                20           0          6,5   True         A   False
1094               61           0          7,4   True         A    True
1342               76           0          7,7   True         A   False
1523               11           1          8,5   True         A   False
1664               92           1          8,4   True         A    True

     pop_level pop_group
151       high       NaN
276       high       NaN
434       high       NaN
480       high       NaN
728       high       NaN
866       high       NaN
1094      high       NaN
1342      high       NaN
1523      high       NaN
1664      high       NaN

[10 rows x 29 columns]

# Худшие треки

In [65]:
print(df.nsmallest(10, "Popularity"))

      Track_ID     Title      Artist      Album  Year       Genre  \
88    Track_88   Song_88  Artist_968  Album_451  1990  Electronic
144  Track_144  Song_144  Artist_194   Album_81  1999   Classical
153  Track_153  Song_153  Artist_272  Album_382  2021  Electronic
157  Track_157  Song_157  Artist_302   Album_20  1988        Jazz
166  Track_166  Song_166  Artist_904  Album_276  1981        Jazz
201  Track_201  Song_201  Artist_391  Album_419  1992        Rock
471  Track_471  Song_471  Artist_866  Album_207  1986   Classical
560  Track_560  Song_560  Artist_552    Album_8  2009         Pop
660  Track_660  Song_660  Artist_789  Album_335  2021     Hip-Hop
733  Track_733  Song_733  Artist_431  Album_169  2015         Pop

     Duration_sec  BPM Key Danceability  ... Record_Label Awards_won  \
88            323   80   E          0,8  ...    Label_118         15
144           358  166  C#         0,61  ...    Label_155         38
153           467   66   G         0,32  ...     Label_15         47
157           484  129  G#         0,93  ...     Label_62          5
166           135  144   B         0,71  ...    Label_133          7
201           470  114   A         0,39  ...      Label_5          5
471           122  194   D         0,14  ...      Label_6         37
560           522  149   G         0,32  ...     Label_72          2
660           139  138  G#            1  ...    Label_116         30
733           132  108   A         0,74  ...    Label_148          7

    Awards_nominated Is_Favorite  User_Rating passed  category is_long  \
88                 1           1          8,9  False         C    True
144               24           0          7,7  False         C    True
153               77           1          6,4  False         C    True
157               69           0          4,8  False         C    True
166               73           0          8,7  False         C   False
201               21           0          3,9  False         C    True
471               74           1          8,6  False         C   False
560               91           1          3,1  False         C    True
660                7           1          6,6  False         C   False
733               63           1          6,6  False         C   False

    pop_level pop_group
88        low       low
144       low       low
153       low       low
157       low       low
166       low       low
201       low       low
471       low       low
560       low       low
660       low       low
733       low       low

[10 rows x 29 columns]

In [66]:
print(df.isnull().sum())

Track_ID             0
Title                0
Artist               0
Album                0
Year                 0
Genre                0
Duration_sec         0
BPM                  0
Key                  0
Danceability         0
Acousticness         0
Instrumentalness     0
Liveness             0
Valence              0
Popularity           0
Streams_million      0
Explicit             0
Country              0
Language             0
Record_Label         0
Awards_won           0
Awards_nominated     0
Is_Favorite          0
User_Rating          0
passed               0
category             0
is_long              0
pop_level            0
pop_group           88
dtype: int64

# Заполнение

In [68]:
df["User_Rating"] = df["User_Rating"].fillna(0)
print(df.head())
# если нет оценки → ставим 0

  Track_ID   Title      Artist      Album  Year    Genre  Duration_sec  BPM  \
0  Track_0  Song_0  Artist_511   Album_83  1972     Rock           139   72
1  Track_1  Song_1  Artist_366   Album_91  1977     Jazz           101   93
2  Track_2  Song_2  Artist_383  Album_467  2003  Hip-Hop           443  107
3  Track_3  Song_3  Artist_323  Album_451  2014     Rock           531  146
4  Track_4  Song_4  Artist_989  Album_154  2009     Jazz           518   99

  Key Danceability  ... Record_Label Awards_won Awards_nominated Is_Favorite  \
0  G#         0,85  ...    Label_119         32               77           1
1   F          0,1  ...     Label_19         43               30           0
2   F         0,36  ...     Label_83          0               32           0
3   B         0,63  ...     Label_80         19               38           0
4   F         0,73  ...    Label_192          7               13           1

   User_Rating passed  category is_long pop_level pop_group
0          9,1  False         C   False       low       low
1          8,1  False         C   False       low       low
2          8,7   True         A    True      high      high
3          8,3  False         C    True       low    medium
4          2,1  False         C    True    medium      high

[5 rows x 29 columns]

# Уникальные значения

In [70]:
print(df["Genre"].unique())

['Rock' 'Jazz' 'Hip-Hop' 'Pop' 'Classical' 'Electronic']

In [71]:
print(df["Genre"].nunique())

6

# value_counts
сколько строк в каждой категории

In [72]:
print(df["Genre"].value_counts())

Genre
Hip-Hop       1741
Rock          1687
Electronic    1673
Pop           1665
Jazz          1629
Classical     1605
Name: count, dtype: int64

# Корреляция (начало анализа)
Связь между числами
показывает:

что влияет на Popularity
есть ли зависимость

In [73]:
print(df.corr(numeric_only=True))

                      Year  Duration_sec       BPM  Popularity  Explicit  \
Year              1.000000     -0.002832 -0.026881    0.013561  0.001569
Duration_sec     -0.002832      1.000000 -0.016676   -0.014243 -0.007073
BPM              -0.026881     -0.016676  1.000000   -0.000063 -0.019049
Popularity        0.013561     -0.014243 -0.000063    1.000000 -0.014700
Explicit          0.001569     -0.007073 -0.019049   -0.014700  1.000000
Awards_won        0.004585      0.012731 -0.001274   -0.020251  0.006426
Awards_nominated -0.012499     -0.001708 -0.000364    0.003330  0.003477
Is_Favorite      -0.002957      0.007502 -0.012789    0.007013 -0.013155
passed            0.006741     -0.008254 -0.008511    0.684291 -0.006529
is_long          -0.010442      0.863311 -0.018456   -0.010910 -0.006529

                  Awards_won  Awards_nominated  Is_Favorite    passed  \
Year                0.004585         -0.012499    -0.002957  0.006741
Duration_sec        0.012731         -0.001708     0.007502 -0.008254
BPM                -0.001274         -0.000364    -0.012789 -0.008511
Popularity         -0.020251          0.003330     0.007013  0.684291
Explicit            0.006426          0.003477    -0.013155 -0.006529
Awards_won          1.000000          0.017834     0.008950 -0.005278
Awards_nominated    0.017834          1.000000     0.014249  0.014292
Is_Favorite         0.008950          0.014249     1.000000 -0.001063
passed             -0.005278          0.014292    -0.001063  1.000000
is_long             0.009950          0.003035     0.005719 -0.007119

                   is_long
Year             -0.010442
Duration_sec      0.863311
BPM              -0.018456
Popularity       -0.010910
Explicit         -0.006529
Awards_won        0.009950
Awards_nominated  0.003035
Is_Favorite       0.005719
passed           -0.007119
is_long           1.000000